name: 'Discord Notify'
description: 'Send a Discord message to a webhook'
inputs:
  webhook_url:
    description: 'Webhook URL from Discord'
    required: true
    default: ''
  title:
    description: 'Title for card'
    required: false
    default: ''
  message:
    description: 'Content of card'
    required: false
    default: ''
  include_image:
    description: 'If action is used in a pull request, attach the preview image for it to the card. Required for custom_image_url'
    required: false
    default: 'false'
  avatar_url:
    description: 'Avatar to use for user'
    required: false
    default: ''
  username:
    description: 'Username to send message as'
    required: false
    default: 'GitHub'
  colour:
    description: 'Colour for the edge of the card in hex'
    required: false
    default: '#3371FF'
  custom_image_url:
    description: 'Include custom image on card, include_image must be true'
    required: false
    default: ''
  title_url:
    description: 'Make the title of the card a link'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
